site_name: Cloud Computing Onboarding
repo_url: 
repo_name: cloud-computing-onboarding
theme:
  name: material
  font:
    text: Museo Sans
  icon:
    repo: fontawesome/brands/github
  logo: assets/cloud-favicon.png
  favicon: assets/cloud-favicon.png
nav:
  - 简介: index.md
  - 虚拟化:
    - 基本概念: virtualization/overview.md
  - KVM:
    - 基本概念: kvm/overview.md
    - 准备KVM实验环境: kvm/prepare-the-experimental-environment.md
 